import convertToRoman from '.'

test('convertToRoman', () => {
  expect(convertToRoman(2)).toEqual('II')
  expect(convertToRoman(3)).toEqual('III')
  expect(convertToRoman(4)).toEqual('IV')
  expect(convertToRoman(5)).toEqual('V')
  expect(convertToRoman(9)).toEqual('IX')
  expect(convertToRoman(12)).toEqual('XII')
  expect(convertToRoman(16)).toEqual('XVI')
  expect(convertToRoman(29)).toEqual('XXIX')
  expect(convertToRoman(44)).toEqual('XLIV')
  expect(convertToRoman(45)).toEqual('XLV')
  expect(convertToRoman(68)).toEqual('LXVIII')
  expect(convertToRoman(83)).toEqual('LXXXIII')
  expect(convertToRoman(97)).toEqual('XCVII')
  expect(convertToRoman(99)).toEqual('XCIX')
  expect(convertToRoman(400)).toEqual('CD')
  expect(convertToRoman(500)).toEqual('D')
  expect(convertToRoman(501)).toEqual('DI')
  expect(convertToRoman(649)).toEqual('DCXLIX')
  expect(convertToRoman(798)).toEqual('DCCXCVIII')
  expect(convertToRoman(891)).toEqual('DCCCXCI')
  expect(convertToRoman(1000)).toEqual('M')
  expect(convertToRoman(1004)).toEqual('MIV')
  expect(convertToRoman(1006)).toEqual('MVI')
  expect(convertToRoman(1023)).toEqual('MXXIII')
  expect(convertToRoman(2014)).toEqual('MMXIV')
  expect(convertToRoman(3999)).toEqual('MMMCMXCIX')
})
